### ISSUE TITLE
Someone please add a README.md file.

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/When-Will-It-Flood-#3]
See https://github.com/codeforamerica/howto/blob/master/Good-READMEs.md for a template.

Note they also already have some templates on how to set up specific dev environments. See some here: https://github.com/codeforamerica/howto

Also cc-ing @differentsmoke & @CyberStrike for this.

**Comment by differentsmoke** [comment]
Let's discuss this at the meetup tomorrow, @CyberStrike and @susanfiu ?

**Comment by differentsmoke** [comment]
@ErnieAtLYD I believe this issue is ripe for closing.
