### ISSUE TITLE
Fix "Identical code" issue in js/test5a.js

### ISSUE THREAD

**Issue by ErnieAtLYD** [Code-for-Miami/When-Will-It-Flood-#5]
Identical code found in 1 other location (mass = 571)

https://codeclimate.com/github/Code-for-Miami/When-Will-It-Flood-/js/test5a.js#issue_5973dfc001111a000100022e

**Comment by CyberStrike** [comment]
This file is to eventually be deleted it was added by @susanfiu for test purposes, which also address #6

**Comment by CyberStrike** [comment]
Fixed with #8
